# Generated by Django 4.2 on 2023-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="subjects_taught",
            new_name="subjects",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="teacher",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
